source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IPaFlickr_Example' do
  pod 'IPaFlickr', :path => '../'

  target 'IPaFlickr_Tests' do
    inherit! :search_paths

    
  end
end
